name: momoschool
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  shared_preferences: ^2.1.2
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  provider: ^6.1.5+1
  vibration: ^3.1.3
  audioplayers: ^6.1.0
  path_drawing: ^1.0.1
  flutter_svg: ^2.0.9  
  svg_path_parser: ^1.1.2        
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/brainstorming.png
    - assets/Calculadora.jpg
    - assets/sudoku.jpg
    - assets/lilac.png
    - assets/lilac.jpg
    - assets/algeria.jpg
    - assets/memoschool.png
    - assets/data/poems.json
    - assets/data/words.json
    - assets/sounds/correct.wav
    - assets/sounds/wrong.wav

  fonts:
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey/Marhey-VariableFont_wght.ttf
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/Readex_Pro/ReadexPro-VariableFont_HEXP,wght.ttf
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PT_Serif/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PT_Serif/PTSerif-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PT_Serif/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PT_Serif/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"